### ISSUE TITLE
Can I stop shimmer on specific bool variable

### ISSUE THREAD

**Issue by benevolent13** [hnvn/flutter_shimmer#6]
I want to stop shimmer effect on a particular bool variable.Is this possible in your plugins?Read.md provides less information regarding it.

**Comment by naiveai** [comment]
In your build() method, just return the widget you want wrapped with Shimmer if it is true, and just the widget if it's false. Pretty easy.

**Comment by feinstein** [comment]
Depending on your widget tree it's not easy and will lead to unreadable code.

**Comment by naiveai** [comment]
@fenstein um, it's just an if statement? Nothing unreadable about it.

**Comment by feinstein** [comment]
Imagine the Shimmer is on top of your widget tree, now you have an if statement that returns duplicated code. Of course the solution is to wrap the child of the shimmer in another widget, but now that's code you didn't have to write in the first place if you just had a boolean.

**Comment by feinstein** [comment]
`Shimmer` is already a `StatefulWidget`, IMO it should have a `ShimmerController` so other parts of the widget tree could stop it if necessary.

**Comment by naiveai** [comment]
No, because widgets are ultimately objects, you don't need to create a wrapper widget for it. Just assign it to a variable in the build function. @feinstein

**Comment by feinstein** [comment]
That's unreadable, instead of having a nice nested widget composition that you can look at and understand in one eye scan, now you have spaghetti composition, where your build function defines stuff here and there and later put them together, making the reader go back and forth in the code.

A `ShimmerController` would be much more appropriate and in line with Flutter, as it has `PageController `, `TextEditingController`, `AnimationController ` and etc.

**Comment by hnvn** [comment]
supported in v1.0.1
